{"uuid": "5e59dfd2-7d18-48d8-9da4-65ea9f8c645d", "children": ["0a69c788-fc38-4215-a14f-830abefcfbf1", "22735f14-059a-4609-bb53-d82e8e87e37c", "80e5bc61-2572-4797-bbf2-68f604a766b0"], "befores": [{"name": "_Class__pytest_setup_class", "status": "passed", "start": 1609316004324, "stop": 1609316005710}], "afters": [{"name": "_Class__pytest_setup_class::0", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'TestPLSqlManipulateData' has no attribute 'conn_id'\n", "trace": "  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 800, in _teardown_yield_fixture\n    next(it)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\_pytest\\python.py\", line 705, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\_pytest\\python.py\", line 632, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\PythonProjects\\me_auto_test\\autoTest\\cases\\hadoop\\plsql\\testplsql.py\", line 36, in teardown_class\n    print(f\"cls.conn_id is {cls.conn_id}\")\n"}, "start": 1609316033530, "stop": 1609316033533}], "start": 1609316004324, "stop": 1609316033533}