{"uuid": "1a992008-ec5c-44c3-a508-8eb166a2214b", "children": ["0f52248c-5516-4533-9ad4-6ea4aad019b0", "6f0998d7-8972-4fb9-8ab0-8ad25c7016f0", "36256035-94ab-4e2d-b512-563dbf61adb7"], "befores": [{"name": "_Class__pytest_setup_class", "status": "passed", "start": 1609315930805, "stop": 1609315931438}], "afters": [{"name": "_Class__pytest_setup_class::0", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'TestPLSqlManipulateData' has no attribute 'conn_id'\n", "trace": "  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 800, in _teardown_yield_fixture\n    next(it)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\_pytest\\python.py\", line 705, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\_pytest\\python.py\", line 632, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\PythonProjects\\me_auto_test\\autoTest\\cases\\hadoop\\plsql\\testplsql.py\", line 35, in teardown_class\n    hp.sdc_dw.drop_database(cls.db_name, cls.conn_id)\n"}, "start": 1609315962153, "stop": 1609315962154}], "start": 1609315930805, "stop": 1609315962154}